name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 2 * * *' # 2am
jobs:
  build:
    name: Rebuild Homepage through Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}